export interface ArcgisFeatureLayerOptions {
  /** Overwrite this value if you want to use a different map layer unique id then the autogenerated. */
  id?: string;
  /** The ArcGIS feature service url. */
  url: string;
  /** Whether include credentials on cross-origin requests or not */
  requestWithCredentials?: boolean;
  /** The ArcGIS feature service access token defined as key-name and a value. */
  accessToken?: { [name: string]: string };
  /** Overwrite this value if you want to use a lower feature request limit as the maximum allowed by ArcGIS feature service. */
  featuresPerRequestLimit?: number;
  /** The list with names of expected feature properties in results. Default is empty. */
  outFields?: string[];
  /** An expression specifying conditions on source features, used when requesting ArcGIS features.*/
  filter?: string;
  /** Overwrite this value if you want to use different minimum zoom level, then specified in ArcGIS feature service. */
  minZoom?: number;
  /** Overwrite this value if you want to use different maximum zoom level, then specified in ArcGIS feature service. */
  maxZoom?: number;
  /** Overwrite this value if you want to use different map layer style, then specified in the ArcGIS feature service. */
  style?: { type: string, paint: {} };
  /** The ID of an existing map layer to insert this layer before, resulting in the new layer appearing visually beneath the existing layer.
   * If this argument is not specified, the layer will be appended to the end of the layers array and appear visually above all other layers. */
  addLayerBefore?: string;
}
