export enum MarkerCategoryBVI {
  ADD_STOP = 'ADD_STOP',
  ALTERNATIVE = 'ALTERNATIVE',
  CANCELLATION = 'CANCELLATION',
  CONSTRUCTION_SITE = 'CONSTRUCTION_SITE',
  DELAY = 'DELAY',
  DISTURBANCE = 'DISTURBANCE',
  END_MESSAGE = 'END_MESSAGE',
  INFORMATION = 'INFORMATION',
  MISSED_CONNECTION = 'MISSED_CONNECTION',
  PLATFORM_CHANGE = 'PLATFORM_CHANGE',
  REROUTE = 'REROUTE',
  TRAIN_REPLACEMENT_BY_BUS = 'TRAIN_REPLACEMENT_BY_BUS',
}
