apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: journey-maps-client
      name: journey-maps-client
    spec:
      replicas: 1
      selector:
        app: journey-maps-client
      template:
        metadata:
          labels:
            app: journey-maps-client
        spec:
          containers:
            - image: docker.bin.sbb.ch/rokas/journey-maps-client-testapp:latest
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: journey-maps-client
              ports:
                - containerPort: 8080
                  name: network-port
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: { }
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: { }
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: journey-maps-client
      name: journey-maps-client
    spec:
      ports:
        - name: network-port
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: journey-maps-client
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: journey-maps-client
      name: journey-maps-client
    spec:
      host: ki-journey-maps-client.app.test04.otc-test.sbb.ch
      port:
        targetPort: network-port
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: journey-maps-client
        weight: 100
      wildcardPolicy: None
metadata:
  name: journey-maps-client-app-template
  labels:
    app: journey-maps-client
